const $ = id => document.getElementById(id);
const state = { variables: {}, lastMessage: "", kb: [] };
function append(role, text) { const node = document.createElement("article"); node.className = role; node.innerHTML = `<b>${role === "user" ? "你" : "助手"}</b><p></p>`; node.querySelector("p").textContent = text; $("messages").appendChild(node); $("messages").scrollTop = $("messages").scrollHeight; }
function evidence(item, note) { const tags = [item.platform, item.industry, item.stage, item.intent, item.language].filter(x => x && x !== "all" && x !== "general").map(x => `<span class="pill">${x}</span>`).join(""); $("evidence").innerHTML = `<div class="card"><h3>${item.title}</h3>${tags}<p class="muted">${item.scene || "未标注场景"}</p><p class="tiny">来源：${item.source_path}</p>${note ? `<p class="warning">${note}</p>` : ""}</div>`; }
function showVariables(names) { const panel = $("variablePanel"); if (!names.length) return panel.classList.add("hidden"); $("variableHint").textContent = `请补充：${names.join("、")}`; $("variableFields").className = "variable-grid"; $("variableFields").innerHTML = names.map(name => `<label>${name}<input data-var="${name}" value="${state.variables[name] || ""}" placeholder="填写 ${name}"></label>`).join(""); panel.classList.remove("hidden"); }
function tokens(text) { const en = text.toLowerCase().match(/[a-z][a-z0-9-]{1,}/g) || []; const zh = text.match(/[\u4e00-\u9fff]{2,}/g) || []; return new Set([...en, ...zh, ...zh.flatMap(word => Array.from({length: Math.max(0, word.length - 1)}, (_, i) => word.slice(i, i + 2)))]); }
function inferPlatform(message) { const aliases = {amazon:["amazon","亚马逊"],shopee:["shopee","虾皮"],shopify:["shopify"],temu:["temu"],"tiktok-shop":["tiktok","抖音"],aliexpress:["aliexpress","速卖通"],ebay:["ebay"],lazada:["lazada"],wish:["wish"],taobao:["taobao","淘宝"],jd:["京东"]}; const lower=message.toLowerCase(); return Object.keys(aliases).find(key => aliases[key].some(x => lower.includes(x))); }
function inferStage(message) { if (/退款|退货|换货|投诉|物流|未收到|refund|return|complaint|tracking|late/i.test(message)) return "aftersales"; if (/订单|发货|支付|赠品|order|ship|payment/i.test(message)) return "sales"; if (/价格|尺码|成分|库存|优惠|产品|price|size|ingredient|stock|discount/i.test(message)) return "presales"; }
function findTemplates(message) { const terms=tokens(message), chosenPlatform=$("platform").value === "all" ? inferPlatform(message) : $("platform").value, industry=$("industry").value, stage=inferStage(message); return state.kb.map(item => { let score=[...terms].filter(x => item.keywords.includes(x)).length; if(chosenPlatform){if(item.platform===chosenPlatform)score+=9;else if(item.platform==="general")score+=2;else if(item.platform!=="all")score-=4} if(industry!=="all"){if(item.industry===industry)score+=5;else if(item.industry==="general")score+=1;else if(item.industry!=="all")score-=2} if(stage && item.stage===stage)score+=4; return {item,score}; }).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>x.item); }
function fill(template, values) { return template.replace(/\[([^\]\n]+)\]/g, (_, key) => values[key]?.trim() || `[${key}]`); }
async function ask(message = state.lastMessage) { const send = $("chatForm").querySelector("button"); send.disabled = true; send.textContent = "检索中…"; try { if(!state.kb.length) throw Error("知识库仍在加载，请稍后重试。"); const results=findTemplates(message); const selected=results[0]; if(!selected) throw Error("暂未找到合适话术。"); const missing=selected.variables.filter(name => !state.variables[name]?.trim()); append("bot", fill(selected.template,state.variables)); evidence(selected, selected.requires_human_review ? "此情形涉及政策、退款、赔偿、医疗/敏感问题或平台争议时，请先人工核实。" : null); showVariables(missing); } catch (error) { append("bot", `抱歉，${error.message}`); } finally { send.disabled = false; send.textContent = "发送"; } }
$("chatForm").addEventListener("submit", event => { event.preventDefault(); const message = $("message").value.trim(); if (!message) return; state.lastMessage = message; state.variables = {}; append("user", message); $("message").value = ""; $("variablePanel").classList.add("hidden"); ask(); });
$("regenerate").addEventListener("click", () => { document.querySelectorAll("[data-var]").forEach(input => state.variables[input.dataset.var] = input.value.trim()); ask(); });
$("clear").addEventListener("click", () => { $("messages").innerHTML = ""; $("evidence").innerHTML = '<p class="muted">发送问题后，这里会显示选用话术及其来源。</p>'; $("variablePanel").classList.add("hidden"); state.variables = {}; });
fetch("knowledge_base.json").then(r=>r.json()).then(x => { state.kb=x.items; $("health").textContent = `知识库已就绪：${x.count} 条话术 · 免费公开模板模式`; }).catch(() => $("health").textContent = "知识库载入失败");
